# TODO: Change package name: Ask Andi
name: flutter_pay
description: Flutter plugin that help you make payments through Apple and Google Pay
version: 0.10.0
# TODO: update to our repo link
homepage: https://github.com/xamelon/flutter_pay

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.7
  effective_dart: ^1.2.3
  freezed: ^0.12.7
  json_serializable: ^3.5.1

flutter:
  plugin:
    # TODO: Change package name
    androidPackage: com.xamelon.flutter_pay
    pluginClass: FlutterPayPlugin
